{
 "title": "NTPD Stats",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(ntp_offset{instance=~\".*\"}, instance)"
    }
   },
   { "name": "percentiles", "label": "percentiles", "query": "5, 10,20,50,80,90,95,99" },
   {
    "name": "rateinterval",
    "label": "Interval Rate",
    "query": "1m,5m,10m,15m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "ntp_remote_peers",
    "label": "ntp_remote_peers",
    "query": {
     "query": "label_values(ntp_remote_delay{instance=~\".*$instance.*\",timeserver=~\"$timeserver\",remote!~\".*pool.ntp.org\"}, remote)"
    }
   },
   {
    "name": "timeserver",
    "label": "timeserver",
    "query": {
     "query": "label_values(ntp_stratum{instance=~\".*$instance.*\",job=\"ntpnew\"}, timeserver)"
    }
   },
   {
    "name": "delta_timeserver",
    "label": "delta_timeserver",
    "query": {
     "query": "label_values(ntp_request_duration_bucket{instance=~\".*$instance.*\"}, timeserver)"
    }
   }
  ]
 },
 "panels": [
  { "title": "INFO", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "table",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "ntp_detail_info{instance=~\".*$instance.*\",timeserver=~\"$timeserver\"}"
    },
    {
     "expr": "ntp_ntp_pool_offset{instance=~\".*$instance.*\",ntp_pool_host=~\"$timeserver\"}"
    },
    {
     "expr": "ntp_ntp_pool_quality_score{instance=~\".*$instance.*\",ntp_pool_host=~\"$timeserver\"}"
    }
   ]
  },
  { "title": "Key Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "$timeserver",
   "type": "stat",
   "gridPos": { "h": 19, "w": 5, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "ntp_offset{instance=~\"$instance.*\",timeserver=~\"$timeserver\"} / 1000  ",
     "legendFormat": "NTP Offset"
    },
    {
     "expr": "ntp_clk_jitter{instance=~\"$instance.*\",timeserver=~\"$timeserver\"}/1000",
     "legendFormat": "Clock Jitter"
    },
    {
     "expr": "ntp_sys_jitter{instance=~\"$instance.*\",timeserver=~\"$timeserver\"}/ 1000  ",
     "legendFormat": "System Jitter"
    },
    {
     "expr": "ntp_clk_wander{instance=~\"$instance.*\",timeserver=~\"$timeserver\"} *1000",
     "legendFormat": "Clock Wander"
    },
    {
     "expr": "ntp_frequency{instance=~\"$instance.*\",timeserver=~\"$timeserver\"}",
     "legendFormat": "frequency"
    },
    {
     "expr": "ntp_ntp_pool_quality_score{instance=~\"$instance.*\",ntp_pool_host=~\"$timeserver\"}",
     "legendFormat": "NTP Pool Quality"
    },
    {
     "expr": "ntp_detail_info{instance=~\"$instance.*\",timeserver=~\"$timeserver\"}",
     "legendFormat": "Ref: {{refid}}"
    },
    {
     "expr": "ntp_detail_info{instance=~\"$instance.*\",timeserver=~\"$timeserver\"}",
     "legendFormat": "{{refid}}"
    }
   ]
  },
  {
   "title": "NTP Offset",
   "type": "graph",
   "gridPos": { "h": 19, "w": 9, "x": 5, "y": 5 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "ntp_offset{instance=~\"$instance.*\",timeserver=~\"$timeserver\"} /1000",
     "legendFormat": "NTP Offset(combined offset of server relative to this host)"
    },
    {
     "expr": "quantile_over_time($percentiles/100, ntp_offset{instance=~\"$instance.*\",timeserver=~\"$timeserver\"}[$rateinterval])/1000 ",
     "legendFormat": "${percentiles}th percentile"
    },
    {
     "expr": "quantile_over_time((100-$percentiles)/100, ntp_offset{instance=~\"$instance.*\",timeserver=~\"$timeserver\"}[$rateinterval])/1000 ",
     "legendFormat": "(1-$percentiles)th percentile"
    },
    {
     "expr": "quantile_over_time(0.50, ntp_offset{instance=~\"$instance.*\",timeserver=~\"$timeserver\"}[$rateinterval])/1000",
     "legendFormat": "50th percentile"
    }
   ]
  },
  {
   "title": "Average over time ($rateinterval) frequency and temerature",
   "type": "graph",
   "gridPos": { "h": 19, "w": 10, "x": 14, "y": 5 },
   "yaxes": [
    { "format": "ppm" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(ntp_frequency{instance=~\"$instance.*\",timeserver=~\"$timeserver\"}[$rateinterval])",
     "legendFormat": "Average over Time frequency ($rateinterval) "
    },
    {
     "expr": "avg_over_time(node_hwmon_temp_celsius{instance=~\"$instance.*\",sensor=\"temp0\"}[$rateinterval])",
     "legendFormat": "Average over Time Temperature {{sensor}} ($rateinterval)  {{timeserver}}"
    },
    {
     "expr": "ntp_frequency{instance=~\"$instance.*\",timeserver=~\"$timeserver\"}",
     "legendFormat": "frequency  {{timeserver}}"
    },
    {
     "expr": "avg_over_time(node_hwmon_temp_celsius{instance=~\"$instance.*\",sensor=\"temp0\"}[5m])",
     "legendFormat": "Temperature {{sensor}}  {{timeserver}}"
    }
   ]
  },
  {
   "title": "Peer jitter",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "ntp_remote_jitter{instance=~\"$instance.*\",remote=~\"$ntp_remote_peers\",timeserver=~\"$timeserver\"} / 1000",
     "legendFormat": "jitter {{remote}} on host"
    }
   ]
  },
  { "title": "Packet Rate", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Packet rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(ntp_packet_rx{instance=~\"$instance.*\"}[$rateinterval])",
     "legendFormat": "NTP Pakets/s "
    },
    {
     "expr": "irate(ntp_curr_version{instance=~\"$instance.*\"}[$rateinterval])",
     "legendFormat": "NTP Pakets/s  V4"
    },
    {
     "expr": "irate(ntp_proc_for_time{instance=~\"$instance.*\"}[$rateinterval])",
     "legendFormat": "Processed for time"
    },
    {
     "expr": "irate(ntp_older_vesion{instance=~\"$instance.*\"}[$rateinterval])",
     "legendFormat": "NTP Pakets/s  V3"
    }
   ]
  },
  {
   "title": "KoD/Ratelimited/Bad packet format-len",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(ntp_rate_limited{instance=~\"$instance.*\"}[$rateinterval])",
     "legendFormat": "Rate limited"
    },
    {
     "expr": "irate(ntp_kod{instance=~\"$instance.*\"}[$rateinterval])",
     "legendFormat": "KoD"
    },
    {
     "expr": "irate(ntp_bad_len{instance=~\"$instance.*\"}[$rateinterval])",
     "legendFormat": "Incorrect packet len/format"
    }
   ]
  },
  { "title": "NTP Offset from NTPD", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "NTP Offset $rateinterval histogram (observed every 2 seconds)",
   "type": "heatmap",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 41 },
   "targets": [
    {
     "expr": "sum(increase(ntp_offset_histogram_bucket{instance=~\"$instance.*\",timeserver=~\"$timeserver\"}[$rateinterval])) by (le) ",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "NTP Offset Histogram Data ${percentiles}th percentile",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 41 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile($percentiles/100, sum(increase(ntp_offset_histogram_bucket{instance=~\"$instance.*\",timeserver=~\"$timeserver\"}[$rateinterval])) by (le))",
     "legendFormat": "${percentiles}th Percentile($rateinterval)"
    },
    {
     "expr": "histogram_quantile(0.5, sum(increase(ntp_offset_histogram_bucket{instance=~\"$instance.*\",timeserver=~\"$timeserver\"}[$rateinterval])) by (le))",
     "legendFormat": "50th Percentile ($rateinterval)"
    },
    {
     "expr": "histogram_quantile((100-$percentiles)/100, sum(increase(ntp_offset_histogram_bucket{instance=~\"$instance.*\",timeserver=~\"$timeserver\"}[$rateinterval])) by (le))",
     "legendFormat": "(100-$percentiles) th Percentile($rateinterval)"
    }
   ]
  },
  {
   "title": "Clock Jitter $rateinterval histogram (observed every 2 seconds)",
   "type": "heatmap",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 52 },
   "targets": [
    {
     "expr": "sum(increase(ntp_clk_jitter_histogram_bucket{instance=~\"$instance.*\",timeserver=~\"$timeserver\"}[$rateinterval])) by (le) ",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Clock Jitter Histogram Data ${percentiles}th percentile",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 52 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile($percentiles/100, sum(increase(ntp_clk_jitter_histogram_bucket{instance=~\"$instance.*\",timeserver=~\"$timeserver\"}[$rateinterval])) by (le))",
     "legendFormat": "${percentiles}th Percentile($rateinterval) $timeserver"
    },
    {
     "expr": "histogram_quantile(0.5, sum(increase(ntp_clk_jitter_histogram_bucket{instance=~\"$instance.*\",timeserver=~\"$timeserver\"}[$rateinterval])) by (le))",
     "legendFormat": "50th Percentile ($rateinterval) $timeserver"
    },
    {
     "expr": "histogram_quantile((100-$percentiles)/100, sum(increase(ntp_clk_jitter_histogram_bucket{instance=~\"$instance.*\",timeserver=~\"$timeserver\"}[$rateinterval])) by (le))",
     "legendFormat": "(100-$percentiles) th Percentile($rateinterval)"
    }
   ]
  },
  {
   "title": "System Jitter $rateinterval histogram (observed every 2 seconds)",
   "type": "heatmap",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 63 },
   "targets": [
    {
     "expr": "sum(increase(ntp_sys_jitter_histogram_bucket{instance=~\"$instance.*\",timeserver=~\"$timeserver\"}[$rateinterval])) by (le) ",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "System Jitter  Histogram Data ${percentiles}th percentile",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 63 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile($percentiles/100, sum(increase(ntp_sys_jitter_histogram_bucket{instance=~\"$instance.*\",timeserver=~\"$timeserver\"}[$rateinterval])) by (le))",
     "legendFormat": "${percentiles}th Percentile($rateinterval) $timeserver"
    },
    {
     "expr": "histogram_quantile(0.5, sum(increase(ntp_clk_jitter_histogram_bucket{instance=~\"$instance.*\",timeserver=~\"$timeserver\"}[$rateinterval])) by (le))",
     "legendFormat": "50th Percentile ($rateinterval) $timeserver"
    },
    {
     "expr": "histogram_quantile((100-$percentiles)/100, sum(increase(ntp_clk_jitter_histogram_bucket{instance=~\"$instance.*\",timeserver=~\"$timeserver\"}[$rateinterval])) by (le))",
     "legendFormat": "(100-$percentiles) th Percentile($rateinterval)"
    }
   ]
  },
  {
   "title": "Clock Wander  $rateinterval histogram (observed every 2 seconds)",
   "type": "heatmap",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 74 },
   "targets": [
    {
     "expr": "sum(increase(ntp_clk_wander_histogram_bucket{instance=~\"$instance.*\",timeserver=~\"$timeserver\"}[$rateinterval])) by (le) ",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Clock Wander Histogram Data ${percentiles}th percentile",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 74 },
   "yaxes": [
    { "format": "conppb" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(increase(ntp_clk_wander_histogram_bucket{instance=~\"$instance.*\"}[$rateinterval])) by (le))",
     "legendFormat": "${percentiles}th Percentile($rateinterval) $timeserver"
    }
   ]
  },
  { "title": "PPS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 85 } },
  {
   "title": "Clock offset from PPS $rateinterval Histogram  (observed every second)",
   "type": "heatmap",
   "description": "$__interval",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 86 },
   "targets": [
    {
     "expr": "sum(increase(gpsd_pps_histogram_bucket{instance=~\"$instance.*\"}[$rateinterval])) by (le) ",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": " (+-) $percentiles Percentile Clock Offset from GPS/PPS (Histogram data)",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 86 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile($percentiles/100, sum(increase(gpsd_pps_histogram_bucket{instance=~\"$instance.*\"}[$rateinterval])) by (le))",
     "legendFormat": "$percentiles th Percentile($rateinterval) $timeserver"
    },
    {
     "expr": "histogram_quantile(0.5, sum(increase(gpsd_pps_histogram_bucket{instance=~\"$instance.*\"}[$rateinterval])) by (le))",
     "legendFormat": "50th Percentile ($rateinterval) $timeserver"
    },
    {
     "expr": "histogram_quantile((100-$percentiles)/100, sum(increase(gpsd_pps_histogram_bucket{instance=~\".*$instance.*\"}[$rateinterval])) by (le))",
     "legendFormat": "(1-$percentiles) th Percentile($rateinterval)"
    }
   ]
  },
  { "title": "Jitter", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 97 } },
  {
   "title": "Clock/System Jitter",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 98 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "ntp_sys_jitter{instance=~\"$instance.*\",timeserver=~\"$timeserver\"}/1000",
     "legendFormat": "${percentiles}th Percentile System Jitter  ($rateinterval) {{timeserver}}"
    },
    {
     "expr": "ntp_clk_jitter{instance=~\"$instance.*\",timeserver=~\"$timeserver\"}/1000",
     "legendFormat": "${percentiles}th Percentile Clock Jitter ($rateinterval) {{timeserver}}"
    }
   ]
  },
  {
   "title": "$percentiles th Percentile Clock/System Jitter",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 98 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "quantile_over_time($percentiles/100, ntp_clk_jitter{instance=~\"$instance.*\",timeserver=~\"$timeserver\"}[$rateinterval])/1000",
     "legendFormat": "${percentiles}th Percentile Clock Jitter ($rateinterval) {{timeserver}}"
    },
    {
     "expr": "quantile_over_time($percentiles/100, ntp_sys_jitter{instance=~\"$instance.*\",timeserver=~\"$timeserver\"}[$rateinterval])/1000",
     "legendFormat": "${percentiles}th Percentile System Jitter  ($rateinterval) {{timeserver}}"
    }
   ]
  },
  {
   "title": "NTP Pool Offset/Quality ",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 6, "y": 106 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ntp_ntp_pool_quality_score{instance=~\"ntp0.*\"} ",
     "legendFormat": "Quality Score {{ntp_pool_host}}"
    },
    {
     "expr": "ntp_ntp_pool_offset{instance=~\"ntp0.*\"} ",
     "legendFormat": "Offset {{ntp_pool_host}}"
    }
   ]
  },
  {
   "title": "Clients Performance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 115 },
   "collapsed": true,
   "panels": [
    {
     "title": "ntpd client request performance ${percentiles}th Percentile",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 116 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.50, sum(rate(ntp_request_duration_bucket{instance=~\"$instance.*\",timeserver=~\"$delta_timeserver\"}[$rateinterval])) by (timeserver,le))",
       "legendFormat": "50th Percentile {{timeserver}}"
      }
     ]
    },
    {
     "title": "ntpd client request performance $delta_timeserver",
     "type": "heatmap",
     "description": "$__interval",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 125 },
     "repeat": "delta_timeserver",
     "targets": [
      {
       "expr": "sum(increase(ntp_request_duration_bucket{instance=~\"$instance.*\",timeserver=~\"$delta_timeserver\"}[$rateinterval])) by (le) ",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Client NTP Requests",
     "type": "graph",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 135 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "irate(ntp_client_requests_total{instance=~\"$instance.*\",timeserver=~\"$delta_timeserver\"}[5m])",
       "legendFormat": "NTP Request per Second {{timeserver}}"
      }
     ]
    }
   ]
  },
  { "title": "Peer details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 116 } },
  {
   "title": "Peer rtt",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 117 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "ntp_remote_delay{instance=~\"$instance.*\",timeserver=~\"$timeserver\",remote=~\"$ntp_remote_peers\"} /1000 > 0",
     "legendFormat": "RTT {{remote}}"
    }
   ]
  },
  {
   "title": "Peer offset",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 117 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "ntp_remote_offset{instance=~\"$instance.*\",timeserver=~\"$timeserver\",remote=~\"$ntp_remote_peers\"} / 1000",
     "legendFormat": "offset {{remote}}"
    }
   ]
  },
  {
   "title": "rootdisp - total dispersion to the primary reference clock",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 130 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "ntp_remote_rootdisp{instance=~\"$instance.*\",remote=~\"$ntp_remote_peers\",timeserver=~\"$timeserver\"} != 0",
     "legendFormat": "{{remote}}"
    }
   ]
  },
  {
   "title": "rootdisp - total dispersion to the primary reference clock",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 130 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "ntp_remote_rootdelay{instance=~\"$instance.*\",remote=~\"$ntp_remote_peers\",timeserver=~\"$timeserver\"} != 0",
     "legendFormat": "{{remote}}"
    }
   ]
  },
  {
   "title": "Remote Precision",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 143 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "ntp_remote_precision{instance=~\"$instance.*\",remote=~\"$ntp_remote_peers\",timeserver=~\"$timeserver\"} != 0",
     "legendFormat": "{{remote}}"
    }
   ]
  },
  {
   "title": "50th Percentile offset",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 143 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "(quantile_over_time(0.5, ntp_remote_offset{instance=~\"$instance.*\",remote=~\"$ntp_remote_peers\",timeserver=~\"$timeserver\"}[$rateinterval]))/1000",
     "legendFormat": "{{remote}}"
    }
   ]
  },
  { "title": "Peer $ntp_remote_peers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 152 }, "repeat": "ntp_remote_peers" },
  {
   "type": "table",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 153 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "(quantile_over_time(0.95, ntp_remote_offset{instance=~\"$instance.*\",remote=~\"$ntp_remote_peers\",timeserver=~\"$timeserver\"}[12h]))/1000",
     "legendFormat": "95th Percentile"
    },
    {
     "expr": "(quantile_over_time(0.5, ntp_remote_offset{instance=~\"$instance.*\",remote=~\"$ntp_remote_peers\",timeserver=~\"$timeserver\"}[12h]))/1000",
     "legendFormat": "50th Percentile"
    },
    {
     "expr": "(quantile_over_time(0.05, ntp_remote_offset{instance=~\"$instance.*\",remote=~\"$ntp_remote_peers\",timeserver=~\"$timeserver\"}[12h]))/1000",
     "legendFormat": "5th Percentile"
    },
    {
     "expr": "ntp_remote_detail_info{instance=~\"$instance.*\",remote=~\"$ntp_remote_peers\",timeserver=~\"$timeserver\"}",
     "legendFormat": "Status {{peer_selection}}, refid {{refid}}"
    }
   ]
  },
  {
   "title": "Peer offset ($ntp_remote_peers)",
   "type": "graph",
   "gridPos": { "h": 11, "w": 18, "x": 6, "y": 153 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "(ntp_remote_offset{instance=~\"$instance.*\",remote=~\"$ntp_remote_peers\",timeserver=~\"$timeserver\"} + (ntp_remote_delay{instance=~\"$instance.*\",remote=~\"$ntp_remote_peers\"}/2))/1000",
     "legendFormat": "Offset + RTT /2 "
    },
    {
     "expr": "(ntp_remote_offset{instance=~\"$instance.*\",remote=~\"$ntp_remote_peers\",timeserver=~\"$timeserver\"}  - (ntp_remote_delay{instance=~\"$instance.*\",remote=~\"$ntp_remote_peers\"}/2) )/1000",
     "legendFormat": "Offset - RTT /2"
    },
    {
     "expr": "(ntp_remote_offset{instance=~\"$instance.*\",remote=~\"$ntp_remote_peers\",timeserver=~\"$timeserver\"})/1000",
     "legendFormat": "Offset "
    }
   ]
  },
  { "title": "Other", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 248 } },
  {
   "title": "frequency offset/clock wander",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 249 },
   "yaxes": [
    { "format": "ppm" }
   ],
   "targets": [
    {
     "expr": "ntp_frequency{instance=~\"$instance.*\",timeserver=~\"$timeserver\"}",
     "legendFormat": "frequency offset (PPM) relative to hardware clock"
    },
    {
     "expr": "ntp_clk_wander{instance=~\"$instance.*\",timeserver=~\"$timeserver\"}*1000",
     "legendFormat": "clock wander (ppb) "
    },
    {
     "expr": "avg_over_time(ntp_frequency{instance=~\"$instance.*\",timeserver=~\"$timeserver\"}[15m])",
     "legendFormat": "Average over Time (frequency)"
    },
    {
     "expr": "avg_over_time(ntp_clk_wander{instance=~\"$instance.*\",timeserver=~\"$timeserver\"}[15m])*1000",
     "legendFormat": "Average over Time wander  (ppb)"
    }
   ]
  }
 ]
}